FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["TooFast.FrontEnd/TooFast.FrontEnd.csproj", "TooFast.FrontEnd/"]
COPY ["TooFast.Contracts/TooFast.Contracts.csproj", "TooFast.Contracts/"]
RUN dotnet restore "TooFast.FrontEnd/TooFast.FrontEnd.csproj"

COPY . .
RUN dotnet publish -c Release -o /app TooFast.FrontEnd/TooFast.FrontEnd.csproj 

FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS publish
WORKDIR /app
COPY --from=build /app ./
ENTRYPOINT ["dotnet", "TooFast.FrontEnd.dll"]
